name: GITHUB_OUTPUT
on: push
jobs:
 share:
  runs-on: windows-latest
  steps:
   - id: source
     run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
#   - env:
#      RESULT: ${{ steps.source.outputs.result }}
#    run: echo "${RESULT}"
