name: Hash functions
on: push
jobs:
 hash:
  runs-on: windows-latest
  steps:
   - uses: actions/checkout@v4
   - run: echo "${HASH}"
     env:
      HASH: ${{ hashFiles('.github/workflows/*.yml') }}
